// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: immunization.sql

package db

import (
	"context"
	"database/sql"
)

const createImmunization = `-- name: CreateImmunization :one
INSERT INTO immunization (
  name
) VALUES (
  $1
) RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateImmunization(ctx context.Context, name sql.NullString) (Immunization, error) {
	row := q.db.QueryRowContext(ctx, createImmunization, name)
	var i Immunization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteImmunization = `-- name: DeleteImmunization :exec
DELETE FROM immunization 
WHERE id = $1
`

func (q *Queries) DeleteImmunization(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteImmunization, id)
	return err
}

const getImmunizationByID = `-- name: GetImmunizationByID :one
SELECT id, name, created_at, updated_at FROM immunization
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetImmunizationByID(ctx context.Context, id int64) (Immunization, error) {
	row := q.db.QueryRowContext(ctx, getImmunizationByID, id)
	var i Immunization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImmunizationByName = `-- name: GetImmunizationByName :one
SELECT id, name, created_at, updated_at FROM immunization
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetImmunizationByName(ctx context.Context, name sql.NullString) (Immunization, error) {
	row := q.db.QueryRowContext(ctx, getImmunizationByName, name)
	var i Immunization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listImmunizations = `-- name: ListImmunizations :many
SELECT id, name, created_at, updated_at FROM immunization
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListImmunizationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListImmunizations(ctx context.Context, arg ListImmunizationsParams) ([]Immunization, error) {
	rows, err := q.db.QueryContext(ctx, listImmunizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Immunization
	for rows.Next() {
		var i Immunization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
