// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type FavFood struct {
	ID        int64          `json:"id"`
	Name      sql.NullString `json:"name"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Immunization struct {
	ID        int64          `json:"id"`
	Name      sql.NullString `json:"name"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Payment struct {
	ID            int64     `json:"id"`
	PaymentMethod string    `json:"payment_method"`
	PaymentStatus string    `json:"payment_status"`
	StartedAt     time.Time `json:"started_at"`
	EndAt         time.Time `json:"end_at"`
	TransactionID int64     `json:"transaction_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Pet struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Age           int32          `json:"age"`
	Gender        interface{}    `json:"gender"`
	Images        sql.NullString `json:"images"`
	Movies        sql.NullString `json:"movies"`
	Contraception sql.NullBool   `json:"contraception"`
	Condition     sql.NullString `json:"condition"`
	OwnerID       int64          `json:"owner_id"`
	TransactionID int64          `json:"transaction_id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type PetFavFood struct {
	ID        int64     `json:"id"`
	PetID     int64     `json:"pet_id"`
	FoodID    int64     `json:"food_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PetImmunization struct {
	ID             int64     `json:"id"`
	PetID          int64     `json:"pet_id"`
	ImmunizationID int64     `json:"immunization_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type PetTag struct {
	ID        int64     `json:"id"`
	PetID     int64     `json:"pet_id"`
	TagID     int64     `json:"tag_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Transaction struct {
	ID                int64          `json:"id"`
	TransactionStatus sql.NullString `json:"transaction_status"`
	PaymentType       sql.NullString `json:"payment_type"`
	PetID             sql.NullString `json:"pet_id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type TransactionDetail struct {
	ID            int64          `json:"id"`
	Name          sql.NullString `json:"name"`
	Price         sql.NullInt32  `json:"price"`
	TransactionID int64          `json:"transaction_id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID   `json:"id"`
	Email     string      `json:"email"`
	Verified  bool        `json:"verified"`
	Password  string      `json:"password"`
	Role      interface{} `json:"role"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type UserDetail struct {
	ID        int64          `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	Name      sql.NullString `json:"name"`
	Gender    interface{}    `json:"gender"`
	Age       sql.NullInt32  `json:"age"`
	Address   sql.NullString `json:"address"`
	Phone     sql.NullInt32  `json:"phone"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
